// Generated by gencpp from file morai_msgs/GhostCmd.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_GHOSTCMD_H
#define MORAI_MSGS_MESSAGE_GHOSTCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct GhostCmd_
{
  typedef GhostCmd_<ContainerAllocator> Type;

  GhostCmd_()
    : header()
    , position()
    , rotation()
    , velocity(0.0)
    , steer_angle(0.0)  {
    }
  GhostCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , rotation(_alloc)
    , velocity(0.0)
    , steer_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rotation_type;
  _rotation_type rotation;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _steer_angle_type;
  _steer_angle_type steer_angle;





  typedef boost::shared_ptr< ::morai_msgs::GhostCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::GhostCmd_<ContainerAllocator> const> ConstPtr;

}; // struct GhostCmd_

typedef ::morai_msgs::GhostCmd_<std::allocator<void> > GhostCmd;

typedef boost::shared_ptr< ::morai_msgs::GhostCmd > GhostCmdPtr;
typedef boost::shared_ptr< ::morai_msgs::GhostCmd const> GhostCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::GhostCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::GhostCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::GhostCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::GhostCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.rotation == rhs.rotation &&
    lhs.velocity == rhs.velocity &&
    lhs.steer_angle == rhs.steer_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::GhostCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::GhostCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GhostCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GhostCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GhostCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GhostCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GhostCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GhostCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::GhostCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a88f5b6531bc1d402f3fb568b617553";
  }

  static const char* value(const ::morai_msgs::GhostCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a88f5b6531bc1d4ULL;
  static const uint64_t static_value2 = 0x02f3fb568b617553ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::GhostCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/GhostCmd";
  }

  static const char* value(const ::morai_msgs::GhostCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::GhostCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 rotation\n"
"\n"
"float64 velocity\n"
"float64 steer_angle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::GhostCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::GhostCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.rotation);
      stream.next(m.velocity);
      stream.next(m.steer_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GhostCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::GhostCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::GhostCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rotation: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steer_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steer_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_GHOSTCMD_H
