// Generated by gencpp from file morai_msgs/Lamps.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_LAMPS_H
#define MORAI_MSGS_MESSAGE_LAMPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct Lamps_
{
  typedef Lamps_<ContainerAllocator> Type;

  Lamps_()
    : header()
    , turn_signal(0)
    , emergency_signal(0)  {
    }
  Lamps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , turn_signal(0)
    , emergency_signal(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _turn_signal_type;
  _turn_signal_type turn_signal;

   typedef int8_t _emergency_signal_type;
  _emergency_signal_type emergency_signal;





  typedef boost::shared_ptr< ::morai_msgs::Lamps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::Lamps_<ContainerAllocator> const> ConstPtr;

}; // struct Lamps_

typedef ::morai_msgs::Lamps_<std::allocator<void> > Lamps;

typedef boost::shared_ptr< ::morai_msgs::Lamps > LampsPtr;
typedef boost::shared_ptr< ::morai_msgs::Lamps const> LampsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::Lamps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::Lamps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::Lamps_<ContainerAllocator1> & lhs, const ::morai_msgs::Lamps_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.turn_signal == rhs.turn_signal &&
    lhs.emergency_signal == rhs.emergency_signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::Lamps_<ContainerAllocator1> & lhs, const ::morai_msgs::Lamps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Lamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Lamps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Lamps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Lamps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Lamps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Lamps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::Lamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59737a050dcd2e90af49d3ccb2c9cc88";
  }

  static const char* value(const ::morai_msgs::Lamps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59737a050dcd2e90ULL;
  static const uint64_t static_value2 = 0xaf49d3ccb2c9cc88ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::Lamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/Lamps";
  }

  static const char* value(const ::morai_msgs::Lamps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::Lamps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int8 turn_signal\n"
"int8 emergency_signal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::Lamps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::Lamps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.turn_signal);
      stream.next(m.emergency_signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lamps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::Lamps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::Lamps_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "turn_signal: ";
    Printer<int8_t>::stream(s, indent + "  ", v.turn_signal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "emergency_signal: ";
    Printer<int8_t>::stream(s, indent + "  ", v.emergency_signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_LAMPS_H
