// Generated by gencpp from file morai_msgs/SetTrafficLight.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SETTRAFFICLIGHT_H
#define MORAI_MSGS_MESSAGE_SETTRAFFICLIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct SetTrafficLight_
{
  typedef SetTrafficLight_<ContainerAllocator> Type;

  SetTrafficLight_()
    : header()
    , traffic_light_index()
    , traffic_light_status(0)  {
    }
  SetTrafficLight_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , traffic_light_index(_alloc)
    , traffic_light_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _traffic_light_index_type;
  _traffic_light_index_type traffic_light_index;

   typedef int16_t _traffic_light_status_type;
  _traffic_light_status_type traffic_light_status;





  typedef boost::shared_ptr< ::morai_msgs::SetTrafficLight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::SetTrafficLight_<ContainerAllocator> const> ConstPtr;

}; // struct SetTrafficLight_

typedef ::morai_msgs::SetTrafficLight_<std::allocator<void> > SetTrafficLight;

typedef boost::shared_ptr< ::morai_msgs::SetTrafficLight > SetTrafficLightPtr;
typedef boost::shared_ptr< ::morai_msgs::SetTrafficLight const> SetTrafficLightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::SetTrafficLight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::SetTrafficLight_<ContainerAllocator1> & lhs, const ::morai_msgs::SetTrafficLight_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.traffic_light_index == rhs.traffic_light_index &&
    lhs.traffic_light_status == rhs.traffic_light_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::SetTrafficLight_<ContainerAllocator1> & lhs, const ::morai_msgs::SetTrafficLight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SetTrafficLight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SetTrafficLight_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SetTrafficLight_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d80dc8acfeb7a2e665a8844435f9a44";
  }

  static const char* value(const ::morai_msgs::SetTrafficLight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d80dc8acfeb7a2eULL;
  static const uint64_t static_value2 = 0x665a8844435f9a44ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/SetTrafficLight";
  }

  static const char* value(const ::morai_msgs::SetTrafficLight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"string traffic_light_index\n"
"int16 traffic_light_status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::SetTrafficLight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.traffic_light_index);
      stream.next(m.traffic_light_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTrafficLight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::SetTrafficLight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::SetTrafficLight_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "traffic_light_index: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.traffic_light_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "traffic_light_status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.traffic_light_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SETTRAFFICLIGHT_H
