// Generated by gencpp from file morai_msgs/VehicleSpecIndex.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VEHICLESPECINDEX_H
#define MORAI_MSGS_MESSAGE_VEHICLESPECINDEX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct VehicleSpecIndex_
{
  typedef VehicleSpecIndex_<ContainerAllocator> Type;

  VehicleSpecIndex_()
    : header()
    , unique_id(0)  {
    }
  VehicleSpecIndex_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , unique_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _unique_id_type;
  _unique_id_type unique_id;





  typedef boost::shared_ptr< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpecIndex_

typedef ::morai_msgs::VehicleSpecIndex_<std::allocator<void> > VehicleSpecIndex;

typedef boost::shared_ptr< ::morai_msgs::VehicleSpecIndex > VehicleSpecIndexPtr;
typedef boost::shared_ptr< ::morai_msgs::VehicleSpecIndex const> VehicleSpecIndexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.unique_id == rhs.unique_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46863621f323f1962bfc6281e3e3269d";
  }

  static const char* value(const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46863621f323f196ULL;
  static const uint64_t static_value2 = 0x2bfc6281e3e3269dULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VehicleSpecIndex";
  }

  static const char* value(const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"int32 unique_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.unique_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpecIndex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VehicleSpecIndex_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "unique_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.unique_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VEHICLESPECINDEX_H
