<?xml version="1.0"?>
<package format="2">
  <name>morai_launch</name>
  <version>1.0.0</version>
  <description>MORAI launch files</description>
  <maintainer email="david@example.com">david</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>morai_msgs</exec_depend>
  <exec_depend>lio_sam</exec_depend>
  <exec_depend>morai_control</exec_depend>
</package>
